---
# vars file for sublime_text

sublime_text_archive: sublime_text_3_build_3083_x64.tar.bz2
sublime_text_url: "http://c758482.r82.cf2.rackcdn.com/{{ sublime_text_archive }}"
sublime_text_install_dir: /opt/sublime_text_3
sublime_text_applications_dir: /usr/share/applications
sublime_text_pkgcntrl_url: "https://sublime.wbond.net/Package%20Control.sublime-package"
