---
# vars file for sublime_text

st3_archive: sublime_text_3_build_3083_x64.tar.bz2
st3_url: "http://c758482.r82.cf2.rackcdn.com/{{ st3_archive }}"
st3_dir: /opt/sublime_text_3
applications_dir: /usr/share/applications
pkgcntrl_url: "https://sublime.wbond.net/Package%20Control.sublime-package"
st3_user_config_dir: "{{ homedir }}/.config/sublime-text/Packages/User"
