---
# tasks file for git

- name: Install Git
  sudo: true
  dnf: pkg=git state=present
  tags: git

- name: Create global gitignore file for current user
  copy:
    src=gitignore_global
    dest={{ git_homedir }}/.gitignore_global
    owner={{ git_username }}
    group={{ git_groupname }}
    mode=0644
  tags: git

- name: Create gitconfig file for current user
  template:
    src=gitconfig.j2
    dest={{ git_homedir }}/.gitconfig
    owner={{ git_username }}
    group={{ git_groupname }}
    mode=0644
  tags: git
