---
# handlers file for samba-server

- name: Restart Samba service
  sudo: true
  service: name=smb state=restarted
  tags: samba-server

- name: Restart NetBIOS service
  sudo: true
  service: name=nmb state=restarted
  tags: samba-server

- name: Reload firewalld
  sudo: true
  service: state=reloaded
  tags: samba-server
