---
# tasks file for docker

- name: Install Docker
  sudo: true
  dnf: name=docker state=present
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: docker

- name: Install Docker
  sudo: true
  yum: name=docker state=present
  when: ansible_pkg_mgr == "yum" or not (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: docker

- name: Start Docker daemon
  sudo: true
  service: enabled=true name=docker state=started
  tags: docker

#follow = This flag indicates that filesystem links, if they exist, should be followed.
#force = force the creation of the symlinks in two cases: the source file does not exist (but will appear later); the destination exists and is a file (so, we need to unlink the "path" file and create symlink to the "src" file in place of it).
#group = name of the group that should own the file/directory, as would be fed to `chown'
#mode = mode the file or directory should be, such as 0644 as would be fed to `chmod'. As of version 1.8, the mode may be specified as a symbolic mode (for example, `u+rwx' or `u=rw,g=r,o=r').
#owner = name of the user that should own the file/directory, as would be fed to `chown'
#path = path to the file being managed.  Aliases: `dest', `name'
#recurse = recursively set the specified file attributes (applies only to state=directory)
#selevel = level part of the SELinux file context. This is the MLS/MCS attribute, sometimes known as the `range'. `_default' feature works as for `seuser'.
#serole = role part of SELinux file context, `_default' feature works as for `seuser'.
#setype = type part of SELinux file context, `_default' feature works as for `seuser'.
#seuser = user part of SELinux file context. Will default to system policy, if applicable. If set to `_default', it will use the `user' portion of the policy if available
#src = path of the file to link to (applies only to `state=link'). Will accept absolute, relative and nonexisting paths. Relative paths are not expanded.
#state = If `directory', all immediate subdirectories will be created if they do not exist, since 1.7 they will be created with the supplied permissions. If `file', the file will NOT be created if it does not exist, see the [copy] or [template] module if you want that behavior.  If `link', the symbolic link will be created or changed. Use `hard' for hardlinks. If `absent', directories will be recursively deleted, and files or symlinks will be unlinked. If `touch' (new in 1.4), an empty file will be created if the c(path) does not exist, while an existing file or directory will receive updated file access and modification times (similar to the way `touch` works from the command line).
- name: Create /docker
  sudo: true
  file: group=root mode=0755 owner=root path=/docker state=directory
  tags: docker
